import { StyleSheet ,Dimensions} from 'react-native';
import { Theme } from '../contexts/ThemeContext';
const { width } = Dimensions.get('window');

export const getStyles = (theme: Theme) =>
  StyleSheet.create({
    /// login style
    loginContainer: {
        flex: 1,
        backgroundColor: theme === 'light' ? '#ffffff' : '#000000',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        borderRadius: 12,
        paddingHorizontal: 15,
        paddingTop: 15,
        marginVertical: 0.05 * width,
        marginHorizontal: 0.05 * width,
        elevation: 3,
        shadowOffset: { width: 1, height: 1 },
        shadowColor: '#333',
        shadowOpacity: 0.3,
        shadowRadius: 2,
      },
     
      loginInput: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        margin: 5,
        width: '90%',
        paddingHorizontal: 10,
      },
      loginButton: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        paddingHorizontal: 10,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'blue',
        margin: 5,
        width: '90%',
      },
      loginText: {
        margin: 5,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'white',
        textAlign: 'center',
      },
      loginTitle: {
        margin: 5,
        fontSize: 30,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'blue',
        textAlign: 'center',
      },
    /// todo list style
      todoContainer: {
        flexGrow: 1,
        width: '100%',
      },
      todoButton: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        paddingHorizontal: 10,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'blue',
        margin: 5,
      },
      todoTitle: {
        fontSize: 30,
        fontWeight: 'bold',
        color: 'gray',
        textAlign: 'center',
        borderRadius: 4,
        elevation: 3,
        borderColor: 'gray',
      },
      todoText: {
        margin: 5,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'white',
        textAlign: 'center',
      },
      todoInput: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        margin: 5,
        paddingHorizontal: 10,
      },
    
      /// todo item style
      itemButton: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 9,
      },
      itemText: {
        margin: 5,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'white',
      },
      rowItem: {
        flex: 1,
        padding: 5,
        textAlign: 'left',
      },
      itemRowContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        width: '97%',
        justifyContent: 'center',
        paddingHorizontal: 5,
        borderRadius: 3,
        elevation: 1,
        margin: 5,
      },
    /// details style
    detailsContainer: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        borderRadius: 12,
        paddingHorizontal: 15,
        paddingTop: 15,
        marginVertical: 0.05 * width,
        marginHorizontal: 0.05 * width,
        elevation: 3,
        shadowOffset: { width: 1, height: 1 },
        shadowColor: '#333',
        shadowOpacity: 0.3,
        shadowRadius: 2,
      },
      detailsTitle: {
        margin: 5,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'black',
        textAlign: 'center',
      },

      detailsDescription: {
        textAlign: 'justify',
        padding: 5,
      },
      details: {
        textAlign: 'center',
        padding: 5,
      },
      detailsButton: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        paddingHorizontal: 5,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'blue',
        margin: 5,
        width: '100%',
      },
      detailsButtonText: {
        margin: 5,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'white',
        textAlign: 'center',
      },
  });
